entry: Fix failure to insert into empty access.conf
A Debian 13's default /etc/security/access.conf contains only comments,
no access rules. This results in a failing puppet run:

    Error: /Stage[main]/Profile_hostbased_ssh::Target/Sshd::Allow_from[sshd allow hostbased ssh]/Pam_access::Entry[Allow user root ssh from 192.168.101.0/24]/Augeas[pam_access/user/+:root:192.168.101.0/24/present]: Could not evaluate: Error sending command 'ins' with params ["access", "before", "/files/etc/security/access.conf/access[last()]"]/Error sending command 'ins' with params ["access", "before", "/files/etc/security/access.conf/access[last()]"]

Translated into raw augeas commands:

    $ augtool -l /etc/security/access.conf
    augtool> context '/files/etc/security/access.conf/'
    augtool> ins access before access[last()]
    error: No match for path expression

There is no match since the file only contains `#comment`s.

This change allows after and before to run successfully on a file
without any rules. -1 rules will still fail as before.

Still fails when puppet runs with --noop but that is a defect I'm
willing to accept.